# Generated by Django 2.2.5 on 2020-08-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20200806_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
