# Generated by Django 2.2.5 on 2020-08-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20200811_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
